# Generated by Django 3.0.1 on 2020-01-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200105_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbnb',
            name='optimal',
            field=models.IntegerField(default=0),
        ),
    ]
